### ISSUE TITLE
modifier question

### ISSUE THREAD

**Issue by chr00ted** [OutsideIT/check_netapp_ontap#103]
Thank you for this Nagios check. I have a usage question if you dont mind: 

If I run:

/usr/local/nagios/libexec/check_netapp_ontap.pl -H netappip --user nagios --password mypassword -o volume_health -n VMware-production

I get a list of several LUNS that are contained in that volume. I tried using option -m to limit to the LUN I wanted, do you know of a way to limit output?

**Comment by kfiresmith** [comment]
`-m include,some_lun_string`

For example, if you have a LUN called 'vsphere13a', you could use `-m include,vsphere13a`.

Beware that this seems to do sub-string matching - for example I do `-m exclude,aggr0` to ensure that the always-at-95% root aggregates are not returned.  Should work the same for volumes.

**Comment by chr00ted** [comment]
Thank you
