### ISSUE TITLE
Snapshot_health usage percentage based on Data Space size

### ISSUE THREAD

**Issue by thisisnotacompanyaccount** [OutsideIT/check_netapp_ontap#21]
When using the snapshot_health option, the percentage of snapshot size usage is calculated from the Snapshot Space Used in relation to the Data Space Total.

Should it not be based on the Total Snapshot Reserve? Because with some volumes the Snapshot Reserve can actually be larger than the Data Space, causing the Snapshot Using 140% space.

So snapshot_health should be calculated within the Total Snapshot Reserve, and volume_health should be calculated within the Data Space Total.

**Comment by thisisnotacompanyaccount** [comment]
I dont know if it is by design or a bug, but I managed to fix it by querying a different variable in the get_snap_space function:
`# $hshVolUsage{$strVolName}{'space-total'} = $nahVol->child_get("volume-space-attributes")->child_get_string("size-available-for-snapshots");

$hshVolUsage{$strVolName}{'space-total'} = $nahVol->child_get("volume-space-attributes")->child_get_string("snapshot-reserve-size");
`

**Comment by willemdh** [comment]
@thisisnotacompanyaccount Please make a pr to the dev branch if you would like to see this added.

**Comment by grind42** [comment]
Seems like this has been fixed in commit be57ac5764ed01e1be88c46664e00d00a01060fc and can be closed.
